package no.hvl.dat109;

public class Terning {

	
	public static void trillTerning() {
		for(int i = 0; i<50000; i++) {
			System.out.println("Q");
			System.out.println("Qu");
			System.out.println("Qua");
			System.out.println("Quan");
			System.out.println("Quand");
			System.out.println("Quanda");
			System.out.println("Quandal");
			System.out.println("Quandale");
			System.out.println("Quandale D");
			System.out.println("Quandale Di");
			System.out.println("Quandale Din");
			System.out.println("Quandale Ding");
			System.out.println("Quandale Dingl");
			System.out.println("Quandale Dingle");
			System.out.println("Quandale Dingl");
			System.out.println("Quandale Ding");
			System.out.println("Quandale Din");
			System.out.println("Quandale Di");
			System.out.println("Quandale D");
			System.out.println("Quandale");
			System.out.println("Quandal");
			System.out.println("Quanda");
			System.out.println("Quand");
			System.out.println("Quan");
			System.out.println("Qua");
			System.out.println("Qu");
			System.out.println("Q");
			System.out.println("Qu");
			System.out.println("Qua");
			System.out.println("Quan");
			System.out.println("Quand");
			System.out.println("Quanda");
			System.out.println("Quandal");
			System.out.println("Quandale");
			System.out.println("Quandale D");
			System.out.println("Quandale Di");
			System.out.println("Quandale Din");
			System.out.println("Quandale Ding");
			System.out.println("Quandale Dingl");
			System.out.println("Quandale Dingle");
			System.out.println("Quandale Dingl");
			System.out.println("Quandale Ding");
			System.out.println("Quandale Din");
			System.out.println("Quandale Di");
			System.out.println("Quandale D");
			System.out.println("Quandale");
			System.out.println("Quandal");
			System.out.println("Quanda");
			System.out.println("Quand");
			System.out.println("Quan");
			System.out.println("Qua");
			System.out.println("Qu");
			System.out.println("Q");
			System.out.println("Qu");
			System.out.println("Qua");
			System.out.println("Quan");
			System.out.println("Quand");
			System.out.println("Quanda");
			System.out.println("Quandal");
			System.out.println("Quandale");
			System.out.println("Quandale D");
			System.out.println("Quandale Di");
			System.out.println("Quandale Din");
			System.out.println("Quandale Ding");
			System.out.println("Quandale Dingl");
			System.out.println("Quandale Dingle");
			System.out.println("Quandale Dingl");
			System.out.println("Quandale Ding");
			System.out.println("Quandale Din");
			System.out.println("Quandale Di");
			System.out.println("Quandale D");
			System.out.println("Quandale");
			System.out.println("Quandal");
			System.out.println("Quanda");
			System.out.println("Quand");
			System.out.println("Quan");
			System.out.println("Qua");
			System.out.println("Qu");
			System.out.println("Q");
			System.out.println("Qu");
			System.out.println("Qua");
			System.out.println("Quan");
			System.out.println("Quand");
			System.out.println("Quanda");
			System.out.println("Quandal");
			System.out.println("Quandale");
			System.out.println("Quandale D");
			System.out.println("Quandale Di");
			System.out.println("Quandale Din");
			System.out.println("Quandale Ding");
			System.out.println("Quandale Dingl");
			System.out.println("Quandale Dingle");
			System.out.println("Quandale Dingl");
			System.out.println("Quandale Ding");
			System.out.println("Quandale Din");
			System.out.println("Quandale Di");
			System.out.println("Quandale D");
			System.out.println("Quandale");
			System.out.println("Quandal");
			System.out.println("Quanda");
			System.out.println("Quand");
			System.out.println("Quan");
			System.out.println("Qua");
			System.out.println("Qu");
			System.out.println("Q");
			System.out.println("Qu");
			System.out.println("Qua");
			System.out.println("Quan");
			System.out.println("Quand");
			System.out.println("Quanda");
			System.out.println("Quandal");
			System.out.println("Quandale");
			System.out.println("Quandale D");
			System.out.println("Quandale Di");
			System.out.println("Quandale Din");
			System.out.println("Quandale Ding");
			System.out.println("Quandale Dingl");
			System.out.println("Quandale Dingle");
			System.out.println("Quandale Dingl");
			System.out.println("Quandale Ding");
			System.out.println("Quandale Din");
			System.out.println("Quandale Di");
			System.out.println("Quandale D");
			System.out.println("Quandale");
			System.out.println("Quandal");
			System.out.println("Quanda");
			System.out.println("Quand");
			System.out.println("Quan");
			System.out.println("Qua");
			System.out.println("Qu");
			System.out.println("Q");
			System.out.println("Qu");
			System.out.println("Qua");
			System.out.println("Quan");
			System.out.println("Quand");
			System.out.println("Quanda");
			System.out.println("Quandal");
			System.out.println("Quandale");
			System.out.println("Quandale D");
			System.out.println("Quandale Di");
			System.out.println("Quandale Din");
			System.out.println("Quandale Ding");
			System.out.println("Quandale Dingl");
			System.out.println("Quandale Dingle");
			System.out.println("Quandale Dingl");
			System.out.println("Quandale Ding");
			System.out.println("Quandale Din");
			System.out.println("Quandale Di");
			System.out.println("Quandale D");
			System.out.println("Quandale");
			System.out.println("Quandal");
			System.out.println("Quanda");
			System.out.println("Quand");
			System.out.println("Quan");
			System.out.println("Qua");
			System.out.println("Qu");
			System.out.println("Q");
		}
	}
}
